
def GetCPPPATH(BSP_ROOT, RTT_ROOT):
	CPPPATH=[
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/case/common",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/case/common/plugin_manage",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/framework/eui/inc",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/common/include",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/adec_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/aenc_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/aenc_component../muxer_component/include",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/arec_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/arender_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/clock_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/demuxer_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/demuxer_component../muxer_component/include",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/h264_decode_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/inc_ex",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/jpeg_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/muxer_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/muxer_component/include",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/omxbase",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/omxbase/inc",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/pano_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/rotate_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/splitter_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/venc_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/vrec_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/component/vrender_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/core",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/core/inc",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/media_extractor",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/mediaplayer",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/mediaplayer/inc",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/recorder",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/framework/recorder/inc",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/h264_decode_component",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/omx_base",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/omx_base/inc",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/oscl",
		"/home/jaylen/xdsm/yizhi/keshi/sa100/ssh_sa100/1_sa100_test/media/test",
		RTT_ROOT + "/bsp/lombo",
		RTT_ROOT + "/bsp/lombo/applications",
		RTT_ROOT + "/bsp/lombo/applications../libraries/libisp/inc",
		RTT_ROOT + "/bsp/lombo/drivers",
		RTT_ROOT + "/bsp/lombo/drivers/cfg",
		RTT_ROOT + "/bsp/lombo/drivers/clk",
		RTT_ROOT + "/bsp/lombo/drivers/cpufreq",
		RTT_ROOT + "/bsp/lombo/drivers/disp",
		RTT_ROOT + "/bsp/lombo/drivers/disp/doss",
		RTT_ROOT + "/bsp/lombo/drivers/disp/dpu",
		RTT_ROOT + "/bsp/lombo/drivers/disp/panel",
		RTT_ROOT + "/bsp/lombo/drivers/dump_reg",
		RTT_ROOT + "/bsp/lombo/drivers/gpadc",
		RTT_ROOT + "/bsp/lombo/drivers/gpio",
		RTT_ROOT + "/bsp/lombo/drivers/i2c",
		RTT_ROOT + "/bsp/lombo/drivers/input",
		RTT_ROOT + "/bsp/lombo/drivers/input/gps",
		RTT_ROOT + "/bsp/lombo/drivers/power",
		RTT_ROOT + "/bsp/lombo/drivers/pwm",
		RTT_ROOT + "/bsp/lombo/drivers/rtc",
		RTT_ROOT + "/bsp/lombo/drivers/spinor",
		RTT_ROOT + "/bsp/lombo/drivers/thermal",
		RTT_ROOT + "/bsp/lombo/drivers/timer",
		RTT_ROOT + "/bsp/lombo/drivers/usb",
		RTT_ROOT + "/bsp/lombo/drivers/vc",
		RTT_ROOT + "/bsp/lombo/drivers/vc/vc_drivcer",
		RTT_ROOT + "/bsp/lombo/drivers/viss",
		RTT_ROOT + "/bsp/lombo/drivers/viss/common",
		RTT_ROOT + "/bsp/lombo/drivers/viss/core",
		RTT_ROOT + "/bsp/lombo/drivers/viss/device",
		RTT_ROOT + "/bsp/lombo/drivers/viss/vic_det",
		RTT_ROOT + "/bsp/lombo/drivers/wdog",
		RTT_ROOT + "/bsp/lombo/include",
		RTT_ROOT + "/bsp/lombo/libraries",
		RTT_ROOT + "/bsp/lombo/libraries/demo/inc",
		RTT_ROOT + "/bsp/lombo/libraries/libisp/inc",
		RTT_ROOT + "/bsp/lombo/libraries/release",
		RTT_ROOT + "/bsp/lombo/pm",
		RTT_ROOT + "/components/cplusplus",
		RTT_ROOT + "/components/dfs/filesystems/devfs",
		RTT_ROOT + "/components/dfs/include",
		RTT_ROOT + "/components/drivers/include",
		RTT_ROOT + "/components/drivers/spi",
		RTT_ROOT + "/components/finsh",
		RTT_ROOT + "/components/libc/compilers/common",
		RTT_ROOT + "/components/libc/compilers/newlib",
		RTT_ROOT + "/components/libc/libdl",
		RTT_ROOT + "/components/libc/pthreads",
		RTT_ROOT + "/components/libc/time",
	]

	return CPPPATH

def GetCPPDEFINES():
	CPPDEFINES=['RT_USING_NEWLIB']
	return CPPDEFINES

